language: python

python:
  - '3.6'
  
os:
  - linux

install:
  - pip install coveralls flake8
  - pip install -r requirements.txt

script:
  - flake8
  - nosetests  --with-coverage --cover-package=chatterbot_voice

after_success:
  - coveralls
